# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
linter:
  rules:
    annotate_overrides: false
    avoid_types_on_closure_parameters: true
    unnecessary_lambdas: true

analyzer:
#   exclude:
#     - path/to/excluded/files/**
