name: fasttrack
description: Release tool for multi app flutter projects
version: 0.1.5
homepage: https://github.com/programmierbar/fasttrack

environment:
  sdk: '>=2.12.0 <4.0.0'

executables:
  fasttrack:

dependencies:
  args: ^2.3.0
  appstore_connect: ^0.1.2
  collection: ^1.15.0
  dart_console: ^1.0.0
  googleapis: ^7.0.0
  googleapis_auth: ^1.3.0
  path: ^1.8.1
  yaml: ^3.1.0

