name: fasttrack
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  http: ^0.13.0
  googleapis: ^2.0.0
  googleapis_auth: ^1.1.0
  dart_jsonwebtoken: ^2.0.0-nullsafety.1
