name: fasttrack
description: Release tool for multi app flutter projects
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  fasttrack:

dependencies:
  args: ^2.1.1
  yaml: ^3.1.0
  googleapis: ^3.0.0
  googleapis_auth: ^1.1.0
  dart_console: ^1.0.0
  appstore_connect:
    path: ../appstore_connect

