name: fasttrack
description: Release tool for multi app flutter projects
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  fasttrack:

dependencies:
  args: ^2.0.0
  yaml: ^3.1.0
  intl: ^0.17.0
  http: ^0.13.1
  googleapis: ^2.0.0
  googleapis_auth: ^1.1.0
  dart_jsonwebtoken: ^2.0.0-nullsafety.2
  dart_console: ^1.0.0
